# Traefik v2.10 Static Configuration
# YouAreCoder.com SaaS Platform

# API and Dashboard
api:
  dashboard: true
  insecure: false

# Entry Points
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt

# Certificate Resolvers
certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@youarecoder.com
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web

# Providers
providers:
  file:
    directory: /etc/traefik/config
    watch: true

# Logging
log:
  level: INFO
  filePath: /var/log/traefik/traefik.log

# Access Logs
accessLog:
  filePath: /var/log/traefik/access.log
  bufferingSize: 100
